class Career {
  const Career(
      {required this.title,
      required this.assetPath,
      this.overview =
          "A graphic designer is a professional who specializes in creating visual content to communicate messages, ideas, and information to a target audience. This can include designing logos, websites, advertising materials, publications, and other types of visual media.\n\nGraphic designers use a variety of tools and software programs to create their work, including Adobe Photoshop, Illustrator, and InDesign, as well as 3D modeling software and other specialized design tools.\n\nIn addition to technical skills, graphic designers also need to be creative thinkers and problem-solvers, able to come up with innovative ideas and solutions to design challenges. They must also have a strong understanding of design principles, such as color theory, typography, and composition, and be able to apply those principles effectively in their work.\n\nGraphic designers may work as part of an in-house design team for a company or organization, or may work as freelancers, serving multiple clients across different industries. They may specialize in specific areas of design, such as branding, web design, or print design, or may have a more generalist approach.\n\nThe job outlook for graphic designers is positive, with steady demand for their services across a variety of industries. According to the Bureau of Labor Statistics, employment of graphic designers is projected to grow 3 percent from 2020 to 2030, about as fast as the average for all occupations.",
      this.skills =
          "1. Creativity: A strong creative ability is essential for a career in graphic design. Designers need to be able to come up with innovative ideas and solutions to design challenges, and have the ability to think outside of the box.\n\n2. Technical proficiency: Graphic designers need to have a strong technical skill set, including proficiency in design software such as Adobe Photoshop, Illustrator, and InDesign. They also need to be familiar with web development technologies such as HTML and CSS.\n\n3. Communication: Effective communication skills are important for graphic designers, as they need to be able to effectively communicate with clients, stakeholders, and other members of a design team.\n\n4. Attention to detail: Graphic designers must have a keen eye for detail and be able to ensure that all aspects of a design are visually appealing and aligned with the overall goals of a project.\n\n5. Time management: Graphic designers often work on multiple projects at once and need to be able to manage their time effectively to meet deadlines and ensure timely completion of projects.\n\n6. Collaboration: Many design projects require collaboration with other designers, stakeholders, and clients. The ability to work well in a team and effectively communicate ideas is essential.\n\n7. Knowledge of design principles: Graphic designers need to have a strong understanding of design principles such as color theory, typography, and composition. They must be able to apply these principles effectively in their work to create visually appealing and effective designs.\n\n8. Adaptability: The design industry is constantly evolving, and graphic designers need to be able to adapt to changes in technology, design trends, and client needs in order to stay competitive and effective in their work.",
      this.tools =
          "1. Adobe Creative Suite: Adobe Creative Suite is a collection of software programs used by designers to create digital designs. Programs in the suite include Photoshop, Illustrator, InDesign, and others.\n\n2. Sketch: Sketch is a vector-based design tool for creating user interfaces, icons, and other digital designs.\n\n3. Figma: Figma is a collaborative interface design tool that allows designers to work together in real time.\n\n4. Canva: Canva is a web-based design tool that provides templates and design elements for creating graphics, presentations, and other visual content.\n\n5. Procreate: Procreate is a digital painting app for iPad that is popular among illustrators and artists.\n\n6. CorelDRAW: CorelDRAW is a vector graphics editor that is popular among designers for creating illustrations, logos, and other graphics.\n\n7. Inkscape: Inkscape is a free, open-source vector graphics editor that can be used to create illustrations, logos, and other graphics.\n\n8. Wacom Tablets: Many designers use Wacom tablets to create digital designs using a pen-like stylus instead of a mouse. This can provide greater precision and control when working on digital designs.\n\n9. 3D modelling software: 3D modelling software such as Autodesk Maya or Blender can be used by designers to create 3D models and visualizations.\n\n10. Typography tools: Typography is a crucial element in many designs, and there are specialized tools such as FontExplorer X or Type kit that can help designers find and manage fonts.\n\n11. Color palette generators: Online color palette generators such as Adobe Color or Coolors can help designers create harmonious color schemes for their designs.\n\n12. Stock image and vector libraries: Many designers use stock image and vector libraries such as Shutterstock or iStock to find high-quality images and graphics to incorporate into their designs.\n\n13. Prototyping tools: Prototyping tools such as InVision or Adobe XD allow designers to create interactive prototypes of their designs for user testing and feedback.\n\n14. Motion graphics software: Motion graphics software such as Adobe After Effects or Apple Motion can be used to create animated graphics and visual effects for video and other digital media.\n\n15. Web development tools: Graphic designers who work on web design projects may also use web development tools such as Sublime Text or Atom to write and edit code."});

  final String title;
  final String assetPath;
  final String overview;
  final String skills;
  final String tools;
}
